### ISSUE TITLE
Don't support Dynamic id on api.js

### ISSUE THREAD

**Issue by ganadara135** [ruddell/generator-jhipster-react-native#288]
**Describe the bug**

Dynamic id of url is basic thing over dealing with api request,
But currently doesn't support.

**Instructions To reproduce**

app/shared/services/api.js

There are only static path api
ex) 
  const getPhoto = (photoId) => api.get('api/photos/' + photoId);
  const getAllPhotos = (options) => api.get('api/photos', options);
  const createPhoto = (photo) => api.post('api/photos', photo);
  const updatePhoto = (photo) => api.post('api/photos', photo);
  const deletePhoto = (photoId) => api.delete('api/photos/' + photoId);

but we need dynamic id path control
ex)
  const updatePhoto = (photo) => api.post('api/photos', photo);
  const updatePhoto = (photo) => api.put('api/photos/' + photo.id, photo);

**JHipster app's `.yo-rc.json`**

{
  "generator-jhipster": {
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "clientFramework": "angularX",
    "serverPort": "8080",
    "serviceDiscoveryType": false,
    "skipUserManagement": false,
    "withAdminUi": true,
    "baseName": "jhipster",
    "buildTool": "maven",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": [],
    "messageBroker": false,
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "skipClient": false,
    "testFrameworks": [],
    "websocket": false,
    "applicationType": "monolith",
    "jhipsterVersion": "7.0.1",
    "skipServer": false,
    "packageFolder": "com/mycompany/myapp",
    "packageName": "com.mycompany.myapp",
    "clientPackageManager": "npm",
    "dtoSuffix": "DTO",
    "entitySuffix": "",
    "reactive": false,
    "clientTheme": "none",
    "clientThemeVariant": "",
    "entities": ["Album", "Photo", "Tag"],
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "blueprints": [
      {
        "name": "generator-jhipster-react-native",
        "version": "4.0.1"
      }
    ],
    "otherModules": [
      {
        "name": "generator-jhipster-react-native",
        "version": "4.0.1"
      }
    ],
    "pages": [],
    "nativeLanguage": "en",
    "creationTimestamp": 1618135434546,
    "reactNative": {
      "reactNativeAppName": "RnApp",
      "detox": true
    },
    "lastLiquibaseTimestamp": 1618135614000
  }
}

**Entity JDL or JSON files**
application {
  config {    
    applicationType monolith,    
    authenticationType jwt,
    prodDatabaseType mysql,
  }
  entities *
}

entity Album {
  title String required,
  description TextBlob,
  created Instant
}

entity Photo {
  title String required,
  description TextBlob,
  image ImageBlob required,
  taken Instant
}

entity Tag {
  name String required minlength(2)
}

relationship ManyToOne {
  Album{user(login)} to User,
  Photo{album(title)} to Album
}

relationship ManyToMany {
  Photo{tag(name)} to Tag{photo}
}

paginate Album with pagination
paginate Photo, Tag with infinite-scroll

**Versions (please complete the following information):**
- JHipster React Native Version:    "react-native": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz",

- `jhipster info` output:

##### **JHipster Version(s)**

```
rn-app@0.0.1 /home/ubuntu/rnHome/org/mobile
└─┬ generator-jhipster-react-native@4.0.1
  └── generator-jhipster@7.0.0-beta.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "clientFramework": "angularX",
    "serverPort": "8080",
    "serviceDiscoveryType": false,
    "skipUserManagement": false,
    "withAdminUi": true,
    "baseName": "jhipster",
    "buildTool": "maven",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": [],
    "messageBroker": false,
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "skipClient": false,
    "testFrameworks": [],
    "websocket": false,
    "applicationType": "monolith",
    "jhipsterVersion": "7.0.1",
    "skipServer": false,
    "packageFolder": "com/mycompany/myapp",
    "packageName": "com.mycompany.myapp",
    "clientPackageManager": "npm",
    "dtoSuffix": "DTO",
    "entitySuffix": "",
    "reactive": false,
    "clientTheme": "none",
    "clientThemeVariant": "",
    "entities": ["Album", "Photo", "Tag"],
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "blueprints": [
      {
        "name": "generator-jhipster-react-native",
        "version": "4.0.1"
      }
    ],
    "otherModules": [
      {
        "name": "generator-jhipster-react-native",
        "version": "4.0.1"
      }
    ],
    "pages": [],
    "nativeLanguage": "en",
    "creationTimestamp": 1618135434546,
    "reactNative": {
      "reactNativeAppName": "RnApp",
      "detox": true
    },
    "lastLiquibaseTimestamp": 1618135614000
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Album {
  title String required
  description TextBlob
  created Instant
}
entity Photo {
  title String required
  description TextBlob
  image ImageBlob required
  taken Instant
}
entity Tag {
  name String required minlength(2)
}
relationship ManyToOne {
  Album{user(login)} to User
  Photo{album(title)} to Album
}
relationship ManyToMany {
  Photo{tag(name)} to Tag{photo}
}

paginate Album with pagination
paginate Photo, Tag with infinite-scroll

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)

git version 2.25.1

node: v14.16.0

npm: 6.14.11

yeoman: 3.1.1

Docker version 20.10.5, build 55c4c88

docker-compose version 1.28.5, build c4eb3a1f

**Comment by ruddell** [comment]
This was fixed in [v4.0.3](https://github.com/ruddell/generator-jhipster-react-native/releases/tag/v4.0.3) in https://github.com/ruddell/generator-jhipster-react-native/commit/56a24ab14467a57706fa1e55b56337fc03ca7b34, the main JHipster generator had a breaking change between the last beta and the v7 release.
